sudo: required
language: minimal
services:
  - docker

before_install:
  - docker build -t $TRAVIS_COMMIT -f Dockerfile.dev .

script:
  - docker run $TRAVIS_COMMIT npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-870665420981"
  bucket_path: "docker-react"
  on:
    branch: "master"
access_key_id : "AWS_ACCESS_KEY"
secret_access_key:
  secure: "AWS_SECRET_KEY"
